server:
  port: 9001
spring:
  application:
    name: tensquare-base  #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa: # SpringData JPA 配置
    database: MySQL
    show‐sql: true
    generate‐ddl: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true #自定义服务名称信息
# redisson lock
redisson:
  address: redis://192.168.25.132:6379
  password :
                                                                 sentinel-addresses: 10.47.91.83:26379,10.47.91.83:26380,10.47.91.83:26381