server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_user?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.25.132
  redis:
    host: 192.168.25.132
    port: 6379
jwt:
  config:
    key: yami
    ttl: 360000
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true #自定义服务名称信息