server: 
  port: 9012
spring: 
  application:  
    name: tensquare-web #指定服务名
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true #自定义服务名称信息

zuul:
  routes:
    tensquare-base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: tensquare-base #指定Eureka注册中心中的服务id
    tensquare-gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: tensquare-gathering #指定Eureka注册中心中的服务id
    tensquare-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: tensquare-article #指定Eureka注册中心中的服务id
    tensquare-friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: tensquare-friend #指定Eureka注册中心中的服务id
    tensquare-qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: tensquare-qa #指定Eureka注册中心中的服务id
    tensquare-recruit: #招聘       
      path: /recruit/** #配置请求URL的请求规则
      serviceId: tensquare-recruit #指定Eureka注册中心中的服务id
    tensquare-spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: tensquare-spit #指定Eureka注册中心中的服务id 
    tensquare-user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: tensquare-user #指定Eureka注册中心中的服务id
    tensquare-search: #搜索
          path: /search/** #配置请求URL的请求规则
          serviceId: tensquare-search #指定Eureka注册中心中的服务id

